name: proxy_setting
repository: https://github.com/ueki-tomohiro/proxy_setting

packages:
  - packages/**
  - "tests/*"

ignore:
  - "packages/**/*example"

command:
  version:
    linkToCommits: true
    branch: main
    workspaceChangelog: true

scripts:
  lint:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.
  analyze: melos exec -- "dart analyze ."
  format:
    run: dart format --output=none --set-exit-if-changed packages tests
  test:
    exec: flutter test
    packageFilters:
      dirExists:
        - test
      ignore:
        - "*example*"
  test-ci:
    exec: flutter test --machine > test.json
    packageFilters:
      dirExists:
        - test
      ignore:
        - "*example*"
  combine: melos exec "\$MELOS_ROOT_PATH/scripts/combine_test.sh"