name: detect_proxy_setting
description: This package detect proxy setting for http. Supported os are Android, iOS, MacOS, Windows.
repository: https://github.com/ueki-tomohiro/proxy_setting/tree/main/packages/detect_proxy_setting
version: 0.0.9

environment:
  sdk: ^3.11.1
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: proxy_setting_android
      ios:
        default_package: proxy_setting_ios
      macos:
        default_package: proxy_setting_macos
      windows:
        default_package: proxy_setting_windows

dependencies:
  flutter:
    sdk: flutter
  proxy_setting_android:  ^0.0.6
  proxy_setting_ios:  ^0.0.5
  proxy_setting_macos:  ^0.0.6
  proxy_setting_platform_interface:  ^0.0.3
  proxy_setting_windows: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3
  plugin_platform_interface: ^2.1.8
  test: ^1.30.0
