name: proxy_setting_ios
description: iOS implementation of the detect_proxy_setting plugin.
repository: https://github.com/ueki-tomohiro/proxy_setting/tree/main/packages/proxy_setting_ios
version: 0.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: detect_proxy_setting
    platforms:
      ios:
        pluginClass: ProxySettingPlugin
        fileName: proxy_setting_ios.dart
        dartPluginClass: ProxySettingiOS

dependencies:
  flutter:
    sdk: flutter
  proxy_setting_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.3
